### ISSUE TITLE
Reference for TNBC subtyping

### ISSUE THREAD

**Issue by wangxlab** [nachoryu/TNBC.CMS#1]
Hi, 
I am using your tool, TNBC.CMS. May I ask a couple of questions?  

1. This tool is not published to a journal yet? 
2. As I read "TNBC.CMS.pdf," you subtyped TNBC into 4 subtypes; 1) mesenchymal-like (MSL), 2) immunomodulatory (IM), 3) luminal AR (LAR) and and 4) stem-like (SL).  Could you tell me the reference paper for this 4 subtyping?   
3. I think you already read this paper, Chen et al. 2012 "TNBCtype: A Subtyping Tool for Triple-Negative Breast Cancer."  Chen et al. subtypes TNBC to 6 sbutyps; 1)2) two basal-like (BL1 and BL2), 3) an immunomodulatory (IM),  4) a mesenchymal (M), 5) a mesenchymal stem-like (MSL), and 6) a luminal androgen receptor (LAR).   I like to match between your 4 subtypes and Chen et al's 6 subtypes.   Can I match your 1) mesenchymal-like (MSL) to Chen et al. 4) M or 5) MSL?  It seems like your 4) Stem-like (SL) can match to Chen et al.'s 5) MSL. Then, probably, I should match your 1) MSL to Chen et al. 4) M subtype??    
4) Could you explain why you named 1) mesenchymal-like as MSL although there is 'stem' in the middle?

Thank you, 
Wang

**Comment by nachoryu** [comment]
Hello,

the article for this tool is "Genomic Characteristics of Triple-Negative Breast Cancer Nominate Molecular Subtypes That Predict
Chemotherapy Response" published at Molecular Cancer Research. This article will address your questions. 

Thanks,

DY
